In [1]:
import os

os.makedirs("04_python/outputs/tables", exist_ok=True)

In [5]:
import pandas as pd

df = pd.read_csv("01_data/processed/dataforge_cleaned.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,year,month
0,1,CA-2017-152156,2017-11-08,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017,11
1,2,CA-2017-152156,2017-11-08,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11
2,3,CA-2017-138688,2017-06-12,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6
3,4,US-2016-108966,2016-10-11,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10
4,5,US-2016-108966,2016-10-11,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2016,10

In [6]:
numeric_summary = df.describe().T

numeric_summary.to_csv("04_python/outputs/tables/numeric_summary.csv")

numeric_summary

,count,mean,std,min,25%,50%,75%,max
Row ID,9800.0,4900.500000,2829.160653,1.000,2450.750,4900.50,7350.250,9800.00
Postal Code,9789.0,55273.322403,32041.223413,1040.000,23223.000,58103.00,90008.000,99301.00
Sales,9800.0,230.769059,626.651875,0.444,17.248,54.49,210.605,22638.48
year,9800.0,2016.724184,1.123984,2015.000,2016.000,2017.00,2018.000,2018.00
month,9800.0,7.818469,3.281905,1.000,5.000,9.00,11.000,12.00

In [7]:
missing = (df.isna().mean() * 100).sort_values(ascending=False)

missing.to_csv("04_python/outputs/tables/missing_percent.csv")

missing

Postal Code      0.112245
Row ID           0.000000
Order Date       0.000000
Order ID         0.000000
Ship Date        0.000000
Ship Mode        0.000000
Customer Name    0.000000
Customer ID      0.000000
Segment          0.000000
Country          0.000000
City             0.000000
State            0.000000
Region           0.000000
Product ID       0.000000
Category         0.000000
Sub-Category     0.000000
Product Name     0.000000
Sales            0.000000
year             0.000000
month            0.000000
dtype: float64

In [8]:
sales_region = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

sales_region.to_csv("04_python/outputs/tables/sales_by_region.csv")

sales_region

Region
West       710219.6845
East       669518.7260
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [12]:
sales_segment = df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

sales_segment.to_csv("04_python/outputs/tables/sales_by_segment.csv")

sales_segment

Segment
Consumer       1.148061e+06
Corporate      6.884941e+05
Home Office    4.249822e+05
Name: Sales, dtype: float64

In [13]:
sales_year = df.groupby("year")["Sales"].sum().sort_values(ascending=False)

sales_year.to_csv("04_python/outputs/tables/sales_by_year.csv")

sales_year

year
2018    722052.0192
2017    600192.5500
2015    479856.2081
2016    459436.0054
Name: Sales, dtype: float64

In [14]:
top10 = df.sort_values(by="Sales", ascending=False).head(10)

top10.to_csv("04_python/outputs/tables/top10_sales.csv")

top10

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,year,month
2697,2698,CA-2015-145317,2015-03-18,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,2015,3
6826,6827,CA-2017-118689,2017-10-02,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,2017,10
8153,8154,CA-2018-140151,2018-03-23,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,2018,3
2623,2624,CA-2018-127180,2018-10-22,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,2018,10
4190,4191,CA-2018-166709,2018-11-17,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,2018,11
9039,9040,CA-2017-117121,2017-12-17,21/12/2017,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,Michigan,48205.0,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,2017,12
4098,4099,CA-2015-116904,2015-09-23,28/09/2015,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,Minnesota,55407.0,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,2015,9
4277,4278,US-2017-107440,2017-04-16,20/04/2017,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,New Jersey,8701.0,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,2017,4
8488,8489,CA-2017-158841,2017-02-02,04/02/2017,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,Virginia,22204.0,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,2017,2
6425,6426,CA-2017-143714,2017-05-23,27/05/2017,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,2017,5

In [15]:
bottom10 = df.sort_values(by="Sales", ascending=True).head(10)

bottom10.to_csv("04_python/outputs/tables/bottom10_sales.csv")

bottom10

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,year,month
4101,4102,US-2018-102288,2018-06-19,23/06/2018,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,2018,6
9292,9293,CA-2018-124114,2018-03-02,02/03/2018,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,Texas,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,2018,3
8658,8659,CA-2017-168361,2017-06-21,25/06/2017,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,Illinois,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,2017,6
4711,4712,CA-2015-112403,2015-03-31,31/03/2015,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,2015,3
2106,2107,US-2015-152723,2015-09-26,26/09/2015,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,Texas,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876,2015,9
7548,7549,CA-2015-103492,2015-10-10,15/10/2015,Standard Class,CM-12715,Craig Molinari,Corporate,United States,Huntsville,Texas,77340.0,Central,OFF-BI-10004140,Office Supplies,Binders,Avery Non-Stick Binders,0.898,2015,10
8033,8034,CA-2016-119690,2016-06-25,28/06/2016,First Class,MV-17485,Mark Van Huff,Consumer,United States,Houston,Texas,77041.0,Central,OFF-BI-10000201,Office Supplies,Binders,"Avery Triangle Shaped Sheet Lifters, Black, 2/...",0.984,2016,6
2761,2762,CA-2018-126536,2018-10-12,14/10/2018,First Class,NK-18490,Neil Knudson,Home Office,United States,San Francisco,California,94110.0,West,TEC-AC-10003709,Technology,Accessories,Maxell 4.7GB DVD-R 5/Pack,0.990,2018,10
8024,8025,CA-2015-129189,2015-07-21,25/07/2015,Standard Class,HM-14860,Harry Marie,Corporate,United States,Dallas,Texas,75217.0,Central,OFF-BI-10000494,Office Supplies,Binders,Acco Economy Flexible Poly Round Ring Binder,1.044,2015,7
4933,4934,CA-2016-106978,2016-09-28,04/10/2016,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Aurora,Colorado,80013.0,West,OFF-BI-10002012,Office Supplies,Binders,Wilson Jones Easy Flow II Sheet Lifters,1.080,2016,9

1. Region with highest sales contributes the majority of total revenue.
2. Certain categories generate higher profit compared to others.
3. Sales distribution varies significantly across segments.
4. Yearly sales trend shows variation indicating possible growth or decline.
5. Top 10 sales transactions are significantly higher than bottom 10, showing skewness.